# Site settings
title: mj's blog
email: mj0225868@gmail.com
description: github blog
baseurl : ""
url: "http://munjeongkang.github.io"

author:
  name     : 'Munjeong Kang'
  email    : mj0225868@gmail.com
  url      : http://munjeongkang.github.io

github: http://munjeongkang.github.io
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
