# Site settings
title: 일상일지
email: mj0225868@gmail.com
description: github blog
baseurl : ""
url: "http://munjeongkang.github.io"

author:
  name     : 'Munjeong Kang'
  email    : mj0225868@gmail.com

mylab: https://github.com/hufsoptblog/hufsoptblog.github.io

disqus_url : http://disqus.com/by/munjeong 
disqus_id : munjeong

#disqus_shortname: "fernandomoreira"
#google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/


